### ISSUE TITLE
Saving completed pomodoros

### ISSUE THREAD

**Issue by SarahNox** [SarahNox/tomato#18]
Given I finished a pomodoro
When I fill in the pomodoro project name
Then data gets stored on the server

**Comment by SarahNox** [comment]
After the relax 5 minutes end, we should redirect the user to /pomodoros/new where they can fill the form to create the pomodoro. Then in the controller we redirect them to the main page to start a new one.

**Comment by sharnik** [comment]
- [ ] create migration to get a "name" field in pomodoro objects
- [ ] create #new in pomodoros controller
- [ ] create view / form for the new pomodoros
- [ ] redirect to the form after finishing a pomodoro

**Comment by SarahNox** [comment]
done

**Comment by sharnik** [comment]
- [ ] Saving pomodoro in the database 
- [ ] Validation - project field needs to be filled
