### ISSUE TITLE
Paginate the pomodoro history list

### ISSUE THREAD

**Issue by SarahNox** [SarahNox/tomato#21]
Given I go to the pomodoro history list
Then I want to see the results paginated

**Comment by SarahNox** [comment]
There's a gem for pagination: https://github.com/amatsuda/kaminari

**Comment by sharnik** [comment]
- [ ] Make sure they're sorted from newest to the oldest (ActiveRecord#order)
- [ ] paginate (20 per page)
- [ ] switch the "last 10 pomodoros" view into a "today's view"

**Comment by SarahNox** [comment]
completed

**Comment by sharnik** [comment]
Don't forget to commit and push. Then you can move on to https://github.com/SarahNox/tomato/issues/25

(I'll close this issue when you show me it works on Monday)
