### ISSUE TITLE
Single user view

### ISSUE THREAD

**Issue by sharnik** [SarahNox/tomato#27]
UsersController #show should show a single User profile.

- [x] instead of loading all the @users in #show action, just load one by params[:id] into @user
- [x] adjust the view not to paginate through @users, but only display data for the @user you set in the controller
- [x] after signup to redirect to user profile

**Comment by SarahNox** [comment]
done

**Comment by sharnik** [comment]
Cool, you can move to #26 and you'll show me how this one works tomorrow.
